# Generated by Django 3.0.6 on 2020-05-31 17:59

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLedgers',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='accounting.Entries')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[accounting.models.validate_positive_amount])),
            ],
            options={
                'db_table': 'account_ledgers_view',
                'managed': False,
            },
        ),
    ]
